name: ci

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          uv pip install pytest ruff wheel twine
          uv pip install .
      - name: checks
        run: |
          uv venv
          ./scripts/checks.sh
      - name: publish
        if: github.event_name == 'push'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv venv
          ./scripts/publish.sh
