name: ci

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          uv pip install pytest ruff wheel twine
          uv pip install .
      - name: checks
        run: |
          source .venv/bin/activate
          echo Checking formatting...
          ruff format --check .
          echo Checking linting...
          ruff check .
          echo Running tests...
          pytest
      - name: publish
        # if: github.event_name == 'push'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          source .venv/bin/activate
          uv build
          uv publish
